"""Oracle-first durable coordinator, bundles, profiles, and worker scaffold."""

from .bundles import (
    BundleValidationError,
    ValidatedJobBundle,
    ValidatedResultBundle,
    canonical_json_bytes,
    compute_checksums,
    extract_input_identity,
    sha256_bytes,
    sha256_file,
    validate_job_bundle,
    validate_result_bundle,
    write_checksums,
)
from .models import (
    AttemptRecord,
    AttemptState,
    CoordinatorError,
    CoordinatorStatus,
    ImportReceipt,
    InvalidTransitionError,
    JobConflictError,
    JobHandle,
    JobRecord,
    JobState,
    Lease,
    StatusSnapshot,
)
from .profiles import (
    PROFILE_REGISTRY,
    PROVIDER_PROFILES,
    RUNTIME_PROFILES,
    ProviderProfile,
    get_provider_profile,
    provider_profile,
)
from .queue import (
    Coordinator,
    CoordinatorQueue,
    DurableCoordinator,
    FilesystemBundleTransport,
    OracleCoordinator,
)
from .worker import LocalWorker, WorkerCommand, WorkerContract, build_worker_command

__all__ = [
    "AttemptRecord",
    "AttemptState",
    "BundleValidationError",
    "Coordinator",
    "CoordinatorError",
    "CoordinatorQueue",
    "CoordinatorStatus",
    "DurableCoordinator",
    "FilesystemBundleTransport",
    "ImportReceipt",
    "InvalidTransitionError",
    "JobConflictError",
    "JobHandle",
    "JobRecord",
    "JobState",
    "Lease",
    "LocalWorker",
    "OracleCoordinator",
    "PROFILE_REGISTRY",
    "PROVIDER_PROFILES",
    "RUNTIME_PROFILES",
    "ProviderProfile",
    "StatusSnapshot",
    "ValidatedJobBundle",
    "ValidatedResultBundle",
    "WorkerCommand",
    "WorkerContract",
    "build_worker_command",
    "canonical_json_bytes",
    "compute_checksums",
    "extract_input_identity",
    "get_provider_profile",
    "provider_profile",
    "sha256_bytes",
    "sha256_file",
    "validate_job_bundle",
    "validate_result_bundle",
    "write_checksums",
]
